name: Run tests

on:
  push:
  schedule:
    # first day of every month at 10:00 UTC
    - cron: 0 10 1 * *

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y bats

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install cvc5
        run: ./get-cvc5.sh

      - name: Install z3
        run: ./get-z3.sh

      - name: gradle test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test

      - name: Build executable
        uses: gradle/gradle-build-action@v2
        with:
          arguments: buildExecutableApp

      - name: Run executable
        run: ./color-unfolder --help

      - name: Run CLI tests
        run: ./cli-tests.bats
